repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terraform_docs
  - repo: https://github.com/shini4i/pre-commit-makefile
    rev: v0.2.0
    hooks:
      - id: makefile-validator
      - id: makefile-readme-updater
        args:
          - --section-name=## Usage
