version: '3'

tasks:
  provision:
    desc: "Provision infrastructure"
    cmds:
      - tofu init -upgrade
      - tofu apply -backup=- -var-file=terraform.tfvars.json -var-file=terraform.tfvars -auto-approve

  destroy:
    desc: "Destroy infrastructure"
    cmds:
      - tofu destroy -var-file=terraform.tfvars.json -var-file=terraform.tfvars -auto-approve
